import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import List

logger = logging.getLogger(__name__)


SCORE_COLORS = {
    "high": "#22c55e",
    "medium": "#f59e0b",
    "low": "#6b7280",
}

SECTOR_COLORS = {
    "ai": "#8b5cf6",
    "fintech": "#06b6d4",
    "healthtech": "#ef4444",
    "edtech": "#f97316",
    "climate": "#22c55e",
    "saas": "#3b82f6",
    "ecommerce": "#ec4899",
    "mobility": "#14b8a6",
    "agritech": "#84cc16",
    "web3": "#a855f7",
    "cybersecurity": "#6366f1",
    "devtools": "#64748b",
}


def build_email_body(relevant_articles: List[dict]) -> str:
    date_str = datetime.now().strftime("%B %d, %Y")

    high_count = sum(1 for a in relevant_articles if a.get("relevance_score") == "high")
    watchlist_count = sum(1 for a in relevant_articles if a.get("watchlist_hits"))

    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a73e8;">Daily Startup Digest</h2>
        <p style="color: #666;">{date_str} | {len(relevant_articles)} relevant articles ({high_count} high priority"""

    if watchlist_count:
        html += f", {watchlist_count} watchlist hits"

    html += f""")</p>
        <hr style="border: 1px solid #eee;">
    """

    for i, item in enumerate(relevant_articles, 1):
        article = item["article"]
        reason = item["reason"]
        category = item["category"].replace("_", " ").title()
        score = item.get("relevance_score", "unknown")
        stage = item.get("stage_mentioned", "unknown")
        border_color = SCORE_COLORS.get(score, "#6b7280")
        sectors = item.get("sectors", [])
        watchlist_hits = item.get("watchlist_hits", [])

        html += f"""
        <div style="margin-bottom: 25px; padding: 15px; border-left: 4px solid {border_color}; background: #f8f9fa;">
            <h3 style="margin: 0 0 8px 0;">
                <a href="{article.link}" style="color: #1a73e8; text-decoration: none;">
                    {article.title}
                </a>
            </h3>
            <p style="margin: 0 0 8px 0; color: #666; font-size: 14px;">
                <strong>Score:</strong> <span style="color: {border_color}; font-weight: bold;">{score.upper()}</span> |
                <strong>Category:</strong> {category} |
                <strong>Stage:</strong> {stage.replace("-", " ").title()}
            </p>
        """

        if watchlist_hits:
            html += f"""
            <p style="margin: 0 0 8px 0; font-size: 13px;">
                <span style="background: #fef3c7; color: #92400e; padding: 2px 8px; border-radius: 4px; font-weight: bold;">WATCHLIST</span>
                <span style="color: #92400e; font-size: 12px; margin-left: 6px;">{", ".join(watchlist_hits)}</span>
            </p>
            """

        if sectors:
            sector_badges = ""
            for sector in sectors:
                color = SECTOR_COLORS.get(sector.lower(), "#6b7280")
                sector_badges += f'<span style="background: {color}22; color: {color}; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; margin-right: 4px;">{sector}</span>'

            html += f"""
            <p style="margin: 0 0 8px 0;">{sector_badges}</p>
            """

        html += f"""
            <p style="margin: 0 0 8px 0; color: #444; font-size: 14px;">
                {reason}
            </p>
            <p style="margin: 0; color: #888; font-size: 12px;">
                {article.summary[:300]}...
            </p>
        </div>
        """

    html += """
        <hr style="border: 1px solid #eee;">
        <p style="color: #999; font-size: 12px;">
            Generated by RSS Digest Tool | Powered by Groq
        </p>
    </body>
    </html>
    """

    return html


def send_digest(
    relevant_articles: List[dict],
    smtp_email: str,
    smtp_password: str,
    recipient_email: str,
) -> bool:
    if not relevant_articles:
        logger.info("No relevant articles to send.")
        return False

    high_count = sum(1 for a in relevant_articles if a.get("relevance_score") == "high")
    watchlist_count = sum(1 for a in relevant_articles if a.get("watchlist_hits"))

    subject = (
        f"Daily Startup Digest - {len(relevant_articles)} relevant ({high_count} high"
    )
    if watchlist_count:
        subject += f", {watchlist_count} watchlist"
    subject += ")"

    body = build_email_body(relevant_articles)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp_email
    msg["To"] = recipient_email

    msg.attach(MIMEText(body, "html"))

    try:
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(smtp_email, smtp_password)
            server.send_message(msg)

        logger.info(f"Digest sent to {recipient_email}")
        return True

    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        raise
