import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import List

logger = logging.getLogger(__name__)


SCORE_COLORS = {
    "high": "#22c55e",
    "medium": "#f59e0b",
    "low": "#6b7280",
}


def build_email_body(relevant_articles: List[dict]) -> str:
    date_str = datetime.now().strftime("%B %d, %Y")

    high_count = sum(1 for a in relevant_articles if a.get("relevance_score") == "high")

    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a73e8;">Daily Startup Digest</h2>
        <p style="color: #666;">{date_str} | {len(relevant_articles)} relevant articles ({high_count} high priority)</p>
        <hr style="border: 1px solid #eee;">
    """

    for i, item in enumerate(relevant_articles, 1):
        article = item["article"]
        reason = item["reason"]
        score = item.get("relevance_score", "unknown")
        border_color = SCORE_COLORS.get(score, "#6b7280")

        html += f"""
        <div style="margin-bottom: 25px; padding: 15px; border-left: 4px solid {border_color}; background: #f8f9fa;">
            <h3 style="margin: 0 0 8px 0;">
                <a href="{article.link}" style="color: #1a73e8; text-decoration: none;">
                    {article.title}
                </a>
            </h3>
            <p style="margin: 0 0 8px 0; color: #666; font-size: 14px;">
                <strong>Score:</strong> <span style="color: {border_color}; font-weight: bold;">{score.upper()}</span>
            </p>
            <p style="margin: 0 0 8px 0; color: #444; font-size: 14px;">
                {reason}
            </p>
            <p style="margin: 0; color: #888; font-size: 12px;">
                {article.summary[:300]}...
            </p>
        </div>
        """

    html += """
        <hr style="border: 1px solid #eee;">
        <p style="color: #999; font-size: 12px;">
            Generated by RSS Digest Tool | Powered by Groq
        </p>
    </body>
    </html>
    """

    return html


def send_digest(
    relevant_articles: List[dict],
    smtp_email: str,
    smtp_password: str,
    recipient_email: str,
) -> bool:
    if not relevant_articles:
        logger.info("No relevant articles to send.")
        return False

    high_count = sum(1 for a in relevant_articles if a.get("relevance_score") == "high")

    subject = (
        f"Daily Startup Digest - {len(relevant_articles)} relevant ({high_count} high)"
    )

    body = build_email_body(relevant_articles)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp_email
    msg["To"] = recipient_email

    msg.attach(MIMEText(body, "html"))

    try:
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(smtp_email, smtp_password)
            server.send_message(msg)

        logger.info(f"Digest sent to {recipient_email}")
        return True

    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        raise
